name: Validate-XML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup ModLinksShaVerifier
        run: Invoke-WebRequest -Uri "https://github.com/hk-modding/ModLinksShaVerifier/releases/download/v1.0/ModLinksShaVerifier.exe" -OutFile "ModLinksShaVerifier.exe"
      - name: Verify ModLinks.xml SHAs
        run: .\ModLinksShaVerifier.exe ModLinks.xml
